[package]
name = "spotify_record"
version = "0.1.0"
authors = ["Tehforsch <Tonipeter92@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
log4rs = "0.12.0"
regex = "1"
subprocess = "0.2.4"
ctrlc = "3.1.4"
dbus = "0.8.2"