[package]
name = "striputary"
version = "0.1.1"
authors = [
    "Toni Peter <mail@tonipeter.de>",
]
edition = "2021"
resolver="2"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = { version = "4.5.11", features = ["derive"] }
dbus = "0.9.7"
futures = "0.3.30"
hound = "3.5.1"
iced = { version = "0.13.1", features = ["canvas"] }
log = "0.4.22"
regex = "1"
rodio = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
shellexpand = "3.1.0"
simplelog = "0.12.2"
time = { version = "0.3.36", default-features = false }
xdg = "2.5.2"
